# Generated by Django 5.2 on 2025-06-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_sample_data'),
        ('locations', '0008_create_missing_tables'),
    ]

    operations = [
    ]
