# Generated by Django 5.2 on 2025-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_merge_0002_sample_data_0008_create_missing_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="website_domain",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="specializations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="insurance_accepted",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="services",
            field=models.TextField(blank=True, null=True),
        ),
    ]
