# Generated by Django 5.2 on 2025-10-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_copy_providers_to_providerv2"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerv2",
            name="accepts_private_pay",
            field=models.BooleanField(
                default=False, help_text="Accepts private pay clients"
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="emergency_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="fax",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="funding_sources",
            field=models.JSONField(
                blank=True,
                help_text="Funding sources accepted (e.g., ['Health Insurance', 'Regional Center', 'Private Pay'])",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="home_based_services",
            field=models.BooleanField(
                default=False, help_text="Offers home-based services"
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="in_person_services",
            field=models.BooleanField(
                default=True, help_text="Offers in-person services"
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Professional license number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="license_type",
            field=models.CharField(
                blank=True,
                help_text="Type of professional license",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="serves_la_county",
            field=models.BooleanField(
                default=True, help_text="Serves Los Angeles County"
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="service_radius_miles",
            field=models.IntegerField(
                blank=True, help_text="Service radius in miles", null=True
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="specific_areas_served",
            field=models.JSONField(
                blank=True,
                help_text="Specific areas/cities served within LA County",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="therapy_types",
            field=models.JSONField(
                blank=True,
                help_text="Types of therapy offered (e.g., ['ABA therapy', 'Speech therapy', 'Occupational therapy'])",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="virtual_services",
            field=models.BooleanField(
                default=False, help_text="Offers virtual/telehealth services"
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="years_experience",
            field=models.IntegerField(
                blank=True, help_text="Years of experience", null=True
            ),
        ),
        migrations.AlterField(
            model_name="providerv2",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="providerv2",
            name="hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="providerv2",
            name="insurance_accepted",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="providerv2",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="providerv2",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
