# Generated by Django 5.2 on 2025-06-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_auto_20250628_1813"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRegionalCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regional_centers",
                        to="locations.provider",
                    ),
                ),
                (
                    "regional_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="locations.regionalcenter",
                    ),
                ),
            ],
            options={
                "db_table": "provider_regional_centers",
            },
        ),
        migrations.AlterUniqueTogether(
            name="providerregionalcenter",
            unique_together={("provider", "regional_center")},
        ),
    ]
