# Generated by Django 5.2 on 2025-06-28 18:32

from django.db import migrations, models
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0012_auto_20250628_1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionalcenter",
            name="service_area",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                help_text="Geographic service area boundary for this regional center",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="regionalcenter",
            name="service_radius_miles",
            field=models.FloatField(
                default=15.0,
                help_text="Approximate service radius in miles (used when no service area polygon is available)",
            ),
        ),
    ]
