# Generated by Django 5.2 on 2025-10-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0012_rename_provider_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerv2",
            name="accepts_regional_center",
            field=models.BooleanField(
                default=False, help_text="Accepts Regional Center funding"
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="accepts_insurance",
            field=models.BooleanField(
                default=False, help_text="Accepts health insurance"
            ),
        ),
        migrations.AddField(
            model_name="providerv2",
            name="center_based_services",
            field=models.BooleanField(
                default=True, help_text="Offers center-based services"
            ),
        ),
    ]
