# Generated by Django 5.2 on 2025-06-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20250628_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='accepts_insurance',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='accepts_private_pay',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='accepts_regional_center',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='accepts_school_funding',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='age_groups_served',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='application_process',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='city',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='diagnoses_served',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='eligibility_requirements',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='location',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='regional_centers_served',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='state',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='telehealth_available',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='waiting_list',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='waiting_list_time',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='website',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='zip_code',
        ),
    ]
