# Generated by Django 5.2 on 2025-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0014_increase_coordinate_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerv2",
            name="latitude",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name="providerv2",
            name="longitude",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11),
        ),
    ]
