# Generated by Django 4.2.14 on 2025-06-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0014_remove_provider_accepts_insurance_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # First, drop the specific GIN index on the areas column
                "DROP INDEX IF EXISTS idx_providers_areas;",
                # Convert the areas field from ARRAY to TEXT
                "ALTER TABLE providers ALTER COLUMN areas TYPE TEXT USING array_to_string(areas, ', ');",
            ],
            reverse_sql=[
                # Reverse operation would convert back to array (if needed)
                "ALTER TABLE providers ALTER COLUMN areas TYPE TEXT[];"
            ],
        ),
    ]
