# Generated by Django 5.2 on 2025-10-27 15:27

from django.db import migrations


def fix_la_regional_center_flags(apps, schema_editor):
    """
    Set is_la_regional_center=True for the 7 LA County Regional Centers.
    This is a data migration to fix a critical bug where all RCs had this flag as False,
    which broke the service_area_boundaries endpoint and prevented the legend and
    provider list from working correctly.
    """
    RegionalCenter = apps.get_model('locations', 'RegionalCenter')

    # The official 7 LA County Regional Centers
    LA_COUNTY_REGIONAL_CENTERS = [
        "North Los Angeles County Regional Center",
        "Eastern Los Angeles Regional Center",
        "Frank D. Lanterman Regional Center",
        "Harbor Regional Center",
        "San Gabriel/Pomona Regional Center",
        "South Central Los Angeles Regional Center",
        "Westside Regional Center",
    ]

    updated_count = 0
    for rc_name in LA_COUNTY_REGIONAL_CENTERS:
        # Update all instances with this name (there may be duplicates)
        updated = RegionalCenter.objects.filter(
            regional_center=rc_name
        ).update(is_la_regional_center=True)
        updated_count += updated

    print(f"✨ Updated {updated_count} Regional Center record(s) to is_la_regional_center=True")


def reverse_fix(apps, schema_editor):
    """
    Reverse the fix by setting is_la_regional_center=False for all LA County RCs.
    This is just for migration rollback purposes.
    """
    RegionalCenter = apps.get_model('locations', 'RegionalCenter')

    LA_COUNTY_REGIONAL_CENTERS = [
        "North Los Angeles County Regional Center",
        "Eastern Los Angeles Regional Center",
        "Frank D. Lanterman Regional Center",
        "Harbor Regional Center",
        "San Gabriel/Pomona Regional Center",
        "South Central Los Angeles Regional Center",
        "Westside Regional Center",
    ]

    for rc_name in LA_COUNTY_REGIONAL_CENTERS:
        RegionalCenter.objects.filter(
            regional_center=rc_name
        ).update(is_la_regional_center=False)


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_increase_coordinate_precision_final'),
    ]

    operations = [
        migrations.RunPython(fix_la_regional_center_flags, reverse_fix),
    ]
