# Generated by Django 5.2 on 2025-10-27 15:32

from django.db import migrations
from django.core.management import call_command


def load_regional_center_fixture(apps, schema_editor):
    """
    Load complete Regional Center data with ZIP codes from fixture.
    This replaces incomplete data in production database.
    """
    # Clear existing Regional Center data to avoid duplicates
    RegionalCenter = apps.get_model('locations', 'RegionalCenter')
    deleted_count = RegionalCenter.objects.all().count()
    RegionalCenter.objects.all().delete()
    print(f"🗑️  Deleted {deleted_count} existing Regional Center records")

    # Load fixture with complete data
    call_command('loaddata', 'regional_centers_complete.json', app_label='locations')

    new_count = RegionalCenter.objects.all().count()
    print(f"✅ Loaded {new_count} Regional Center records with complete data")


def reverse_load(apps, schema_editor):
    """
    Reverse by clearing all Regional Center data.
    This is just for migration rollback - data would need to be restored from backup.
    """
    RegionalCenter = apps.get_model('locations', 'RegionalCenter')
    RegionalCenter.objects.all().delete()
    print("⚠️  Regional Center data cleared - restore from backup if needed")


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_fix_la_regional_center_flags'),
    ]

    operations = [
        migrations.RunPython(load_regional_center_fixture, reverse_load),
    ]
