# Generated by Django 5.2 on 2025-10-28 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_drop_old_provider_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerfundingsource',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_funding_sources', to='locations.providerv2'),
        ),
        migrations.AlterField(
            model_name='providerregionalcenter',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_centers', to='locations.providerv2'),
        ),
        migrations.AlterField(
            model_name='providerservicemodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_service_models', to='locations.providerv2'),
        ),
        migrations.AlterField(
            model_name='providerinsurancecarrier',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_insurance_carriers', to='locations.providerv2'),
        ),
        migrations.AlterField(
            model_name='providerfundingsource',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='locations.fundingsource'),
        ),
        migrations.AlterField(
            model_name='providerinsurancecarrier',
            name='insurance_carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='locations.insurancecarrier'),
        ),
        migrations.AlterField(
            model_name='providerservicemodel',
            name='service_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='locations.servicedeliverymodel'),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
