# Generated by Django 5.2 on 2025-10-29 18:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0024_add_location_pointfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerv2",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="regionalcenter",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="regionalcenter",
            name="service_area",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                geography=True,
                help_text="Geographic service area boundary for this regional center",
                null=True,
                srid=4326,
            ),
        ),
    ]
