# Generated by Django 5.2 on 2025-10-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0025_delete_provider_providerv2_location_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Provider",
        ),
    ]
