# Generated by Django 5.2 on 2025-10-30 18:34

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop unused fields from ProviderV2 model
    These fields are not used in the UI or API
    """

    dependencies = [
        ('locations', '0029_populate_postgis_location_field'),
    ]

    operations = [
        # Drop unused boolean flags (not displayed in UI)
        migrations.RemoveField(
            model_name='providerv2',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='accepts_private_pay',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='accepts_regional_center',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='accepts_insurance',
        ),

        # Drop service delivery flags (not displayed)
        migrations.RemoveField(
            model_name='providerv2',
            name='in_person_services',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='virtual_services',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='home_based_services',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='center_based_services',
        ),

        # Drop unused text fields
        migrations.RemoveField(
            model_name='providerv2',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='funding_sources',
        ),

        # Drop license fields (not shown in UI)
        migrations.RemoveField(
            model_name='providerv2',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='license_type',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='years_experience',
        ),

        # Drop additional contact fields (not used)
        migrations.RemoveField(
            model_name='providerv2',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='emergency_phone',
        ),

        # Drop service area fields (not used)
        migrations.RemoveField(
            model_name='providerv2',
            name='service_radius_miles',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='serves_la_county',
        ),
        migrations.RemoveField(
            model_name='providerv2',
            name='specific_areas_served',
        ),
    ]
