# Generated by Django 5.2 on 2026-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0030_drop_unused_provider_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providerv2',
            index=models.Index(fields=['name'], name='providerv2_name_idx'),
        ),
        migrations.AddIndex(
            model_name='providerv2',
            index=models.Index(fields=['therapy_types'], name='providerv2_therapy_gin'),
        ),
        migrations.AddIndex(
            model_name='providerv2',
            index=models.Index(fields=['age_groups'], name='providerv2_age_gin'),
        ),
        migrations.AddIndex(
            model_name='providerv2',
            index=models.Index(fields=['diagnoses_treated'], name='providerv2_diag_gin'),
        ),
    ]
