# Generated by Django 5.2 on 2026-01-06 02:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0031_add_providerv2_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerv2",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
