# Generated by Django 5.2 on 2025-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_update_regionalcenter_to_match_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="areas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
