# XcodeGen project specification
# Install: brew install xcodegen
# Generate: cd chla-ios && xcodegen generate

name: CHLA-iOS
options:
  bundleIdPrefix: com.chla
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: "NDD Resource Map"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.healthcare-fitness"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "NDD Resource Map uses your location to find healthcare providers near you."
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  CHLA-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CHLA-iOS
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nddresources.map
        PRODUCT_NAME: "NDD Resource Map"
    info:
      path: CHLA-iOS/Resources/Info.plist
      properties:
        CFBundleDisplayName: "NDD Resource Map"
        NSLocationWhenInUseUsageDescription: "NDD Resource Map uses your location to find healthcare providers near you."
        NSLocationAlwaysAndWhenInUseUsageDescription: "NDD Resource Map uses your location to find healthcare providers near you."
        ITSAppUsesNonExemptEncryption: false
        UILaunchScreen: {}

schemes:
  CHLA-iOS:
    build:
      targets:
        CHLA-iOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
