# Generated by Django 5.2 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResponseReportThrottleWindow",
            fields=[
                (
                    "window_start",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("request_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "response report throttle window",
                "verbose_name_plural": "response report throttle windows",
            },
        ),
        migrations.CreateModel(
            name="AssistantResponseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsafe_or_inappropriate", "Unsafe or inappropriate"),
                            ("inaccurate_or_misleading", "Inaccurate or misleading"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reported_response", models.TextField()),
                ("locale", models.CharField(max_length=16)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android")],
                        max_length=16,
                    ),
                ),
                ("app_version", models.CharField(max_length=32)),
                (
                    "response_fingerprint_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "assistant response report",
                "verbose_name_plural": "assistant response reports",
                "ordering": ("-created_at",),
            },
        ),
    ]
