name: Quick CI (Fast Validation)

# Runs FAST checks on every push/PR
# Full deployment only on main branch

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.12'

jobs:
  # Quick validation (2-3 minutes max)
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: maplocation/requirements.txt

      - name: Python syntax check
        run: |
          cd maplocation
          python -m compileall -q .

      - name: Django check (no database)
        run: |
          cd maplocation
          pip install Django django-cors-headers djangorestframework django-filter graphene-django
          python manage.py check --deploy || true
        env:
          DB_NAME: test_db
          DB_USER: test
          DB_HOST: localhost
          DJANGO_SECRET_KEY: test-key
          DJANGO_DEBUG: 'false'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: map-frontend/package-lock.json

      - name: Frontend lint check
        run: |
          cd map-frontend
          npm ci
          npm run lint || echo "No lint errors"

      - name: Check for debug statements
        run: |
          echo "Checking for console.log..."
          ! grep -r "console.log" map-frontend/src --include="*.vue" --include="*.ts" || echo "Warning: console.log found"
          
          echo "Checking for print statements..."
          ! grep -r "print(" maplocation/locations --include="*.py" | grep -v "DEBUG" || echo "Warning: print() found"

  # Only run full deployment on main branch
  deploy:
    name: Deploy to Production
    needs: quick-checks
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/deploy-production.yml
    secrets: inherit

